### ISSUE TITLE
Review `when` for inclusion in SDK third_party DEPS.

### ISSUE THREAD

**Issue by pq** [dart-lang/when#6]
I've tagged a release `0.2.0` and would like to include it in the SDK DEPS to add it to `third_party/pkg`.  This is required in order to pull `cli_util` into the SDK.  (Note that `which` is being vetted in the same way -- see dart-lang/which#9.)

`cli_util` is used by *at least* the following core dart services:

  * `analyzer_cli`
  * `dartdoc`
  * `linter`
  * `analysis_server`

Please consider this a review of the whole corpus.  I'll respond to concerns with a separate pull request and then update the tag before referencing it in DEPS.

Reviewers:

@devoncarew
@sethladd

**Comment by devoncarew** [comment]
Please add a copyright header to https://github.com/dart-lang/when/blob/master/example/read_json_file.dart (and other files).

**Comment by devoncarew** [comment]
I think we can remove the https://github.com/dart-lang/when/blob/master/drone.sh script.

**Comment by devoncarew** [comment]
https://github.com/dart-lang/when/blob/master/pubspec.yaml should have an sdk constraint.

**Comment by devoncarew** [comment]
You should also analyze the example and test files: https://github.com/dart-lang/when/blob/master/tool/travis.sh#L11

**Comment by devoncarew** [comment]
Can you file an issue to track reverting the specific version of dart_coveralls? https://github.com/dart-lang/when/blob/master/tool/travis.sh#L20

**Comment by devoncarew** [comment]
WDYT about adding a return type here (`dynamic`)? https://github.com/dart-lang/when/blob/master/lib/when.dart#L27

@pq @seaneagan

**Comment by devoncarew** [comment]
Consider package rename: `wherefore`?

**Comment by devoncarew** [comment]
No showstoppers - lgtm :)

**Comment by pq** [comment]
Thanks!

Here's a PR with the fixes: https://github.com/dart-lang/when/pull/9

Tracking bug here: https://github.com/dart-lang/when/issues/10

**Comment by sethladd** [comment]
lgtm
